In [19]:
import numpy as np
import pandas as pd

In [20]:
df = pd.read_csv("../data/raw/09007bd.csv",sep=";",encoding="latin1")

df

  Tipología penal\tPeriodos:\tComunidades autónomas\tTotal
0  III. TOTAL INFRACCIONES PENALES\tenero-septiem...

In [21]:
df.describe().T

,count,unique,top,freq
Tipología penal\tPeriodos:\tComunidades autónomas\tTotal,1,1,III. TOTAL INFRACCIONES PENALES\tenero-septiem...,1